server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffManageSystem?useSSL=false&characterEncoding=utf-8
    username: root
    password: WN13512506305
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file: staffManager.log
# path: c:/myLog/staffManager