#设置本服务访问所需的用户名密码，开启服务登陆验证
security:
#  user:
#    name: admin
#    password: admin123
  basic:
    enabled: false
management:
  security:
    enabled: false
logging:
  #设置输出日志文件名
  file: admin.log
  #设置输出日志路径
  path: /home/SugardaLogs