zuul:
  routes:
    api-a:
      path: /api/user/**
      serviceId: USERMANAGE-SERVICE
#    api-b:
#      path: /api/department/**
#      serviceId: service-feign
security:
  basic:
    enabled: false
management:
  security:
    enabled: false