zuul:
  routes:
    api-a:
      path: /api/user/**
      serviceId: USERMANAGER-SERVICE
    api-b:
      path: /api/department/**
      serviceId: service-feign
security:
  basic:
    enabled: false
management:
  security:
    enabled: false