spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uaaservice?characterEncoding=utf8&useSSL=false
    password: ${MYSQL_PASSWORD}
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #配置数据库类型
    database: MYSQL
    #配置是否打印sql
    show-sql: true
    #Hibernate相关配置
    hibernate:
      #配置级联等级
      ddl-auto: update
      naming:
        #命名策略
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
security:
  user:
    #设置安全登陆验证，用户名
    name: ${UAA_SERVICE_USER_NAME:admin}
    #设置安全登陆验证，密码
    password: ${UAA_SERVICE_USER_PASSWORD:admin123}
  basic:
    enabled: true
management:
  security:
    enabled: true
logging:
  #设置输出日志文件名
  file: ../uaa.log
  #设置输出日志路径
  #path: /home/SugardaLogs