spring:
  datasource:
    url: jdbc:mysql://sh-cdb-dxj88iwb.sql.tencentcdb.com:63098/user_database?characterEncoding=utf8&useSSL=false
    password: ${MYSQL_PASSWORD}
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #配置数据库类型
    database: MYSQL
    #配置是否打印sql
    show-sql: true
    #Hibernate相关配置
    hibernate:
      #配置级联等级
      ddl-auto: update
      naming:
        #命名策略
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  redis:
    # 配置redis集群访问地址
    cluster:
      nodes: 10.32.200.1:6379,10.32.200.2:6379,10.32.200.3:6379,10.32.200.4:6379,10.32.200.5:6379,10.32.200.6:6379
    # 配置redis访问地址,单节点
    #url: 10.32.200.1
    # 配置redis访问所需密码
    password: ${REDIS_PASSWORD}
    # Redis数据库索引（默认为0）
    database: 0
    # Redis连接地址
    #host: localhost
    # Redis连接端口
    #port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
security:
  user:
    #设置安全登陆验证，用户名
    name: ${UAA_SERVICE_USER_NAME:admin}
    #设置安全登陆验证，密码
    password: ${UAA_SERVICE_USER_PASSWORD:admin123}
  basic:
    enabled: true
management:
  security:
    enabled: true
logging:
  #设置输出日志文件名
  file: ../uaa.log
  #设置输出日志路径
  #path: /home/SugardaLogs
Token:
  StayTime: 2