spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_database?characterEncoding=utf-8&useSSL=false
    password: ${MYSQL_PASSWORD}
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #配置数据库类型
    database: MYSQL
    #配置是否打印sql
    show-sql: true
    #Hibernate相关配置
    hibernate:
      #配置级联等级
      ddl-auto: update
      naming:
        #命名策略
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
#logging:
#  #设置输出日志文件名
#  file: ../userManage.log
  #设置输出日志路径
  #path: /home/SugardaLogs