spring:
  datasource:
    url: jdbc:mysql://sh-cdb-dxj88iwb.sql.tencentcdb.com:63098/user_database?characterEncoding=utf8&useSSL=false
    password: ${MYSQL_PASSWORD}
    username: root
    driver-class-name: com.mysql.jdbc.Driver
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
#logging:
#  #设置输出日志文件名
#  file: ../userManage.log
  #设置输出日志路径
  #path: /home/SugardaLogs