#设置tomcat服务端口号
server:
  port: 8761
  #设置服务名称
spring:
  application:
    name: eureka-service

eureka:
  server:
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 1800
  instance:
    hostname: localhost
    prefer-ip-address: true
  #注册中心不需要注册自己
  client:
    register-with-eureka: false
    #注册中心不需要去发现服务
    fetch-registry: false
    #设置服务注册中心的URL
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
security:
  user:
    name: admin
    password: admin123